### ISSUE TITLE
Attention: overrides /var/www when installed on domain root

### ISSUE THREAD

**Issue by njoyard** [matlink/gitweb_ynh#2]
Just a simple warning : if you install this app on a domain root, it will **replace** any existing /var/www directory.

I just lost its whole content after installing and removing this 😢 and found out by inspecting auth.log:

Edit: not sure if it was replaced at installation or removed at removal. Or both. Figures...
```
Nov  2 12:48:41 gozer sudo:     root : TTY=unknown ; PWD=/var/cache/yunohost/from_file/gitweb_ynh-29efb4ed39fd5f168b52a5ce54950efb2df0d822/scripts ; USER=root ; COMMAND=/bin/ln -s /usr/share/gitweb /var/www/
Nov  2 12:49:34 gozer sudo:     root : TTY=unknown ; PWD=/tmp/yunohost_remove/scripts ; USER=root ; COMMAND=/bin/rm -rf /var/www/
̀
```

**Comment by matlink** [comment]
This app is unmaintained anymore. I'm sorry for your loss :(
